[project]
dependencies = [ "snakemake>=9.17,<10", "snakemake-interface-common>=1.23.0,<2", "snakemake-interface-scheduler-plugins>=2.0.2,<3", "pulp>=2.3.1,<3.4", ]
name = "snakemake-scheduler-plugin-milp"
requires-python = ">=3.11,<4.0"
version = "0.1.1"

authors = [
  { name = "Johannes Köster", email = "johannes.koester@uni-due.de" },
  { name = "Filipe G. Vieira" },
]
maintainers = [
  { name = "Johannes Köster", email = "johannes.koester@uni-due.de" },
  { name = "Filipe G. Vieira" },
]
description = "A Snakemake scheduler plugin using Mixed-Integer Linear Programming (MILP)."
readme = "README.md"
license = "MIT"
keywords = ["snakemake", "plugin", "scheduler", "ilp", "milp", "mixed-integer linear programming"]

[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling",]

[dependency-groups]
dev = [ "ruff", "coverage", "pytest", "twine", "build",]

[project.urls]
Repository = "https://github.com/snakemake/snakemake-scheduler-plugin-milp"
Documentation = "https://snakemake.github.io/snakemake-plugin-catalog/plugins/scheduler/milp.html"

[tool.pixi.workspace]
channels = [ "conda-forge",]
platforms = [ "linux-64",]

[tool.pixi.tasks]

[tool.pixi.pypi-dependencies.snakemake_scheduler_plugin_milp]
path = "."
editable = true

[tool.pixi.environments.dev]
features = [ "dev",]

[tool.pixi.feature.dev.tasks]
lint = "ruff check"
format = "ruff format"
test = "pytest --cov=snakemake-scheduler-plugin-milp --cov-report=xml:coverage-report/coverage.xml --cov-report=term-missing tests/tests.py"
build = "python -m build"
check-build = { cmd = "python -m twine check dist/*", depends-on = ["build"] }
